main/urls.py
from django.urls import path
from main import views, transfer, transaction, payment_request, credit_card

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),

    # Transfers
    path("search-account/", transfer.search_users_account_number, name="search-account"),
    path("amount-transfer/<account_number>/", transfer.AmountTransfer, name="amount-transfer"),
    path("amount-transfer-process/<account_number>/", transfer.AmountTransferProcess, name="amount-transfer-process"),
    path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.TransferConfirmation, name="transfer-confirmation"),
    path("transfer-process/<account_number>/<transaction_id>/", transfer.TransferProcess, name="transfer-process"),
    path("transfer-completed/<account_number>/<transaction_id>/", transfer.TransferCompleted, name="transfer-completed"),

    # transactions
    path("transactions/", transaction.transaction_lists, name="transactions"),
    path("transaction-detail/<transaction_id>/", transaction.transaction_detail, name="transaction-detail"),

    # Payment Request
    path("request-search-account/", payment_request.SearchUsersRequest, name="request-search-account"),
    path("amount-request/<account_number>/", payment_request.AmountRequest, name="amount-request"),
    path("amount-request-process/<account_number>/", payment_request.AmountRequestProcess, name="amount-request-process"),
    path("amount-request-confirmation/<account_number>/<transaction_id>/", payment_request.AmountRequestConfirmation, name="amount-request-confirmation"),
    path("amount-request-final-process/<account_number>/<transaction_id>/", payment_request.AmountRequestFinalProcess, name="amount-request-final-process"),
    path("amount-request-completed/<account_number>/<transaction_id>/", payment_request.RequestCompleted, name="amount-request-completed"),

    # Request Settlement
    path("settlement-confirmation/<account_number>/<transaction_id>/", payment_request.settlement_confirmation, name="settlement-confirmation"),
    path("settlement-processing/<account_number>/<transaction_id>/", payment_request.settlement_processing, name="settlement-processing"),
    path("settlement-completed/<account_number>/<transaction_id>/", payment_request.settlement_completed, name="settlement-completed"),
    path("delete-request/<account_number>/<transaction_id>/", payment_request.delete_payment_request, name="delete-request"),

    # Credit Card URLS
    path("card/<card_id>/", credit_card.card_detail, name="card-detail"),
    path("fund-credit-card/<card_id>/", credit_card.fund_credit_card, name="fund-credit-card"),
    path("withdraw_fund/<card_id>/", credit_card.withdraw_fund, name="withdraw_fund"),
    path("delete_card/<card_id>/", credit_card.delete_card, name="delete_card"),

]

my_fundz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('accounts.urls')),
    path('userauth/', include('userauth.urls')),
    path('accounts/', include('allauth.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauth/urls.py
from django.urls import path
from userauth import views

app_name = "userauth"

urlpatterns = [
    path("", views.account, name="account"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("kyc-reg/", views.kyc_registration, name="kyc-reg"),
    path('change-pin/', views.change_pin, name='change-pin'),
]

main/models.py
from django.db import models
from accounts.models import User 
from userauth.models import Account
from shortuuid.django_fields import ShortUUIDField


TRANSACTION_TYPE = (
    ("transfer", "Transfer"),
    ("recieved", "Recieved"),
    ("withdraw", "withdraw"),
    ("refund", "Refund"),
    ("request", "Payment Request"),
    ("none", "None")
)

TRANSACTION_STATUS = (
    ("failed", "failed"),
    ("completed", "completed"),
    ("pending", "pending"),
    ("processing", "processing"),
    ("request_sent", "request_sent"),
    ("request_settled", "request settled"),
    ("request_processing", "request processing"),

)


CARD_TYPE = (
    ("master", "master"),
    ("visa", "visa"),
    ("verve", "verve"),

)


class Transaction(models.Model):
    transaction_id = ShortUUIDField(unique=True, length=15, max_length=20, prefix="TRN")
   
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="user")
    amount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    description = models.CharField(max_length=1000, null=True, blank=True)
   
    reciever = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="reciever")
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="sender")
   
    reciever_account = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True, related_name="reciever_account")
    sender_account = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True, related_name="sender_account")

    status = models.CharField(choices=TRANSACTION_STATUS, max_length=100, default="pending")
    transaction_type = models.CharField(choices=TRANSACTION_TYPE, max_length=100, default="none")

    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=False, null=True, blank=True)

    def __str__(self):
        try:
            return f"{self.user}"
        except Exception as e:  # Specify Exception class
            return f"Transaction - Error: {e}"  # Handle the error


class CreditCard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    card_id = ShortUUIDField(unique=True, length=5, max_length=20, prefix="CARD", alphabet="1234567890")

    name = models.CharField(max_length=100)
    number = models.IntegerField()
    month = models.IntegerField()
    year = models.IntegerField()
    cvv = models.IntegerField()

    amount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)

    card_type = models.CharField(choices=CARD_TYPE, max_length=20, default="master")
    card_status = models.BooleanField(default=True)

    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}"

main/forms.py
from django import forms
from main.models import CreditCard

class CreditCardForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Card Holder Name"}))
    number = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"Card Number"}))
    month = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"Expiry Month"}))
    year = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"Expiry Year"}))
    cvv = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"CVV"}))

    class Meta:
        model = CreditCard
        fields = ['name', 'number', 'month', 'year', 'cvv', 'card_type']

main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <!-- head start -->
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="shortcut icon"
      href="{% static 'images/displayicon.png' %}"
      type="image/x-icon"
    />
    <link rel="icon" href="{% static 'images/displayicon.png' %}" type="image/x-icon" />

    <title>
      MyFundz -{% block title %}

      {% endblock %}
    </title>
    {% include 'main/css.html' %}
  </head>
  <!-- head end -->

  <body>
    <!-- start preloader -->
    {% comment %} <div class="preloader" id="preloader"></div> {% endcomment %}
    <!-- end preloader -->

    <!-- Scroll To Top Start -->
    <a href="javascript:void(0)" class="scrollToTop"><i class="fas fa-angle-double-up"></i></a>
    <!-- Scroll To Top End -->

    <!-- header and nav start-->
    {% include 'main/navbar.html' %}
    <!-- END nav -->

    {% block content %}

    {% endblock content%}

    {% include 'main/js.html' %}
  </body>
</html>

main/templates/main/css.html
{% load static %}

<link rel="shortcut icon" href="{% static 'images/fav.png" type="image/x-icon' %}" />
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" />
<link rel="stylesheet" href="{% static 'css/plugin/nice-select.css' %}" />
<link rel="stylesheet" href="{% static 'css/plugin/magnific-popup.css' %}" />
<link rel="stylesheet" href="{% static 'css/plugin/slick.css' %}" />
<link rel="stylesheet" href="{% static 'css/arafat-font.css' %}" />
<link rel="stylesheet" href="{% static 'css/plugin/animate.css' %}" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" />

main/templates/main/footer.html
{% load static %}
<!-- Footer Area Start -->
<footer class="footer-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="newsletter">
                    <div class="section-area mb-30 dark-sec text-center">
                        <h3 class="title">Subscribe to Our Newsletter</h3>
                    </div>
                    <form action="#">
                        <div class="form-group d-flex align-items-center">
                            <input type="text" placeholder="Your Email Address">
                            <button><img src="{% static 'images/icon/arrow-right-2.png' %}" alt="icon"></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer-area pt-120">
            <div class="footer-top">
                <div class="row align-items-center">
                    <div class="col-sm-6 d-flex justify-content-center justify-content-sm-start">
                        <div class="menu-item">
                            <ul class="footer-link d-flex align-items-center">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Support</a></li>
                                <li><a href="#">Fees</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-link d-flex justify-content-sm-end justify-content-center align-items-center">
                            <a href="javascript:void(0)"><img src="{% static 'images/icon/facebook.png' %}" alt="icon"></a>
                            <a href="javascript:void(0)"><img src="{% static 'images/icon/linkedin.png' %}" alt="icon"></a>
                            <a href="javascript:void(0)"><img src="{% static 'images/icon/instagram.png' %}" alt="icon"></a>
                            <a href="javascript:void(0)"><img src="{% static 'images/icon/twitter.png' %}" alt="icon"></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-bottom">
                <div class="row justify-content-between align-items-center">
                    <div class="col-md-6 col-sm-8 d-flex justify-content-center justify-content-sm-start order-sm-0 order-1">
                        <div class="copyright text-center text-sm-start">
                            <p> Copyright © 2023 <a href="https://github.com/preciousimo">MyFundz.</a> All Rights Reserved.</p>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-4">
                        <div class="menu-item">
                            <ul class="footer-link d-flex justify-content-sm-end justify-content-center align-items-center">
                                <li><a href="#">Terms</a></li>
                                <li><a href="#">Privacy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Area End -->

main/templates/main/js.html
{% load static %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/fontawesome.js' %}"></script>
<script src="{% static 'js/plugin/slick.js' %}"></script>
<script src="{% static 'js/plugin/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/plugin/counter.js' %}"></script>
<script src="{% static 'js/plugin/waypoint.min.js' %}"></script>
<script src="{% static 'js/plugin/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/plugin/wow.min.js' %}"></script>
<script src="{% static 'ss/plugin/plugin.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

main/templates/main/navbar.html
{% load static %}
<style>
  .navbar-brandd {
    font-size: 50px;
    font-weight: bold;
    text-decoration: none;
    color: #4b23c0;
    transition: color 0.3s;
  }

  .navbar-brandd:hover {
    color: #76b5ff;
  }
</style>

<!-- header-section start -->
<header class="header-section">
  <div class="overlay">
    <div class="container">
      <div class="row d-flex header-area">
        <nav class="navbar navbar-expand-lg navbar-light">
          <a class="navbar-brandd" href="{% url 'main:index' %}"> MyFundz </a>
          <button
            class="navbar-toggler collapsed"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbar-content"
          >
            <i class="fas fa-bars"></i>
          </button>
          <div
            class="collapse navbar-collapse justify-content-end"
            id="navbar-content"
          >
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown main-navbar">
                <a
                  class="nav-link dropdown-toggle"
                  href="javascript:void(0)"
                  data-bs-toggle="dropdown"
                  data-bs-auto-close="outside"
                  >Personal</a
                >
                <ul class="dropdown-menu main-menu shadow">
                  <li><a class="nav-link" href="{% url 'main:index' %}">Discover Personal</a></li>
                  <li><a class="nav-link" href="#">Transfer & Spend</a></li>
                  <li><a class="nav-link" href="#">Save</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown main-navbar">
                <a
                  class="nav-link dropdown-toggle"
                  href="javascript:void(0)"
                  data-bs-toggle="dropdown"
                  data-bs-auto-close="outside"
                  >Business
                </a>
                <ul class="dropdown-menu main-menu shadow">
                  <li>
                    <a class="nav-link" href="#">Discover Business</a>
                  </li>
                  <li>
                    <a class="nav-link" href="#">Business Registration</a>
                  </li>
                  <li><a class="nav-link" href="#">Integrations</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown main-navbar">
                <a
                  class="nav-link dropdown-toggle"
                  href="javascript:void(0)"
                  data-bs-toggle="dropdown"
                  data-bs-auto-close="outside"
                  >Company
                </a>
                <ul class="dropdown-menu main-menu shadow">
                  <li><a class="nav-link" href="#">About Us</a></li>
                  <li><a class="nav-link" href="#">Career</a></li>
                  <li><a class="nav-link" href="#">Blog</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown main-navbar">
                <a
                  class="nav-link dropdown-toggle"
                  href="javascript:void(0)"
                  data-bs-toggle="dropdown"
                  data-bs-auto-close="outside"
                  >Help
                </a>
                <ul class="dropdown-menu main-menu shadow">
                  <li>
                    <a class="nav-link" href="#">Get Help</a>
                  </li>
                  <li>
                    <a class="nav-link" href="#">Scam Awareness</a>
                  </li>
                  <li>
                    <a class="nav-link" href="#">FAQs</a>
                  </li>
                  <li>
                    <a class="nav-link" href="#">Security</a>
                  </li>
                  <li>
                    <a class="nav-link" href="#">Contact Us</a>
                  </li>
                </ul>
              </li>
            </ul>
            <div
              class="right-area header-action d-flex align-items-center max-un"
            >
              {% if request.user.is_authenticated %}
              <a href="{% url 'userauth:dashboard' %}" class="login">Dashboard</a>

              <a href="{% url 'logout' %}" class="cmn-btn"
                >Sign Out
                <i class="icon-d-right-arrow-2"></i>
              </a>

              {% else %}
              <a href="{% url 'login' %}" class="login">Login</a>
              <a href="{% url 'signup' %}" class="cmn-btn"
                >Sign Up
                <i class="icon-d-right-arrow-2"></i>
              </a>
              {% endif %}
            </div>
          </div>
        </nav>
      </div>
    </div>
  </div>

  <!-- alert start -->

  {% if messages %} {% for m in messages %}
  <div class="alert alert-{{m.tags}}">
    <strong>{{m}}</strong>
  </div>
  {% endfor %} {% endif %}
  <script>
    setTimeout(() => {
      ₦(".alert").alert("close");
    }, 4000);
  </script>

  <!-- alert end -->
</header>
<!-- header-section end -->